[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=1
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=Install YT-DLP ULTRA MAX 9000 to C:\YTDLP?
DisplayLicense=C:\Users\ZeroPoint\Projects\YT-DLP ULTRA MAX 9000\YT-DLP ULTRA MAX 9000\License agreement.txt
FinishMessage=Questions? Comments? Developer Contact Info: allofasuddenithappens@gmail.com
TargetName=C:\Users\ZeroPoint\Projects\YT-DLP ULTRA MAX 9000\YT-DLP ULTRA MAX 9000.EXE
FriendlyName=YT-DLP ULTRA MAX 9000
AppLaunched=powershell.exe -ExecutionPolicy Bypass -File INSTALL.ps1
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="License agreement.txt"
FILE1="youtube-search.bat"
FILE2="youtube-search.ps1"
FILE3="yt-dlp-gui.exe"
FILE4="INSTALL.ps1"
[SourceFiles]
SourceFiles0=C:\Users\ZeroPoint\Projects\YT-DLP ULTRA MAX 9000\YT-DLP ULTRA MAX 9000\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
%FILE4%=
